package com.ameen.app.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF006A67)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFF9EF0EB)
val OnPrimaryContainerLight = Color(0xFF00201E)
val SecondaryLight = Color(0xFF4A6361)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E6)
val OnSecondaryContainerLight = Color(0xFF051F1E)
val BackgroundLight = Color(0xFFFAFDFC)
val OnBackgroundLight = Color(0xFF191C1B)
val SurfaceLight = Color(0xFFFAFDFC)
val OnSurfaceLight = Color(0xFF191C1B)
val SurfaceVariantLight = Color(0xFFDAE5E3)
val OnSurfaceVariantLight = Color(0xFF3F4948)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val OutlineLight = Color(0xFF6F7978)

val PrimaryDark = Color(0xFF82D4D0)
val OnPrimaryDark = Color(0xFF003735)
val PrimaryContainerDark = Color(0xFF00504D)
val OnPrimaryContainerDark = Color(0xFF9EF0EB)
val SecondaryDark = Color(0xFFB1CCCA)
val OnSecondaryDark = Color(0xFF1C3533)
val SecondaryContainerDark = Color(0xFF324B4A)
val OnSecondaryContainerDark = Color(0xFFCCE8E6)
val BackgroundDark = Color(0xFF191C1B)
val OnBackgroundDark = Color(0xFFE0E3E2)
val SurfaceDark = Color(0xFF191C1B)
val OnSurfaceDark = Color(0xFFE0E3E2)
val SurfaceVariantDark = Color(0xFF3F4948)
val OnSurfaceVariantDark = Color(0xFFBEC9C7)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val OutlineDark = Color(0xFF899392)
